version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/sofomo/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - RAILS_ENV=production
      - IPSTACK_API_KEY=<ipstack-key>
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
